//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGarage.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyGarage.Resources.Languages.LangRes", typeof(LangRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        internal static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add next check reminder:.
        /// </summary>
        internal static string AddNextCheck {
            get {
                return ResourceManager.GetString("AddNextCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        internal static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average distance per week.
        /// </summary>
        internal static string AverageOdoLabel {
            get {
                return ResourceManager.GetString("AverageOdoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Type:.
        /// </summary>
        internal static string BodyType {
            get {
                return ResourceManager.GetString("BodyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chassis.
        /// </summary>
        internal static string Chassis {
            get {
                return ResourceManager.GetString("Chassis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check at .
        /// </summary>
        internal static string CheckAtKm {
            get {
                return ResourceManager.GetString("CheckAtKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertible.
        /// </summary>
        internal static string Convertible {
            get {
                return ResourceManager.GetString("Convertible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupe.
        /// </summary>
        internal static string Coupe {
            get {
                return ResourceManager.GetString("Coupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossover.
        /// </summary>
        internal static string Crossover {
            get {
                return ResourceManager.GetString("Crossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel.
        /// </summary>
        internal static string Diesel {
            get {
                return ResourceManager.GetString("Diesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric.
        /// </summary>
        internal static string Electric {
            get {
                return ResourceManager.GetString("Electric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields need to be filled in..
        /// </summary>
        internal static string EmptyFields {
            get {
                return ResourceManager.GetString("EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Name.
        /// </summary>
        internal static string EmptyName {
            get {
                return ResourceManager.GetString("EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine.
        /// </summary>
        internal static string Engine {
            get {
                return ResourceManager.GetString("Engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry deleted..
        /// </summary>
        internal static string EntryDeleted {
            get {
                return ResourceManager.GetString("EntryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry updated..
        /// </summary>
        internal static string EntryUpdated {
            get {
                return ResourceManager.GetString("EntryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by type.
        /// </summary>
        internal static string FilterByType {
            get {
                return ResourceManager.GetString("FilterByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel type:.
        /// </summary>
        internal static string FuelType {
            get {
                return ResourceManager.GetString("FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatchback.
        /// </summary>
        internal static string Hatchback {
            get {
                return ResourceManager.GetString("Hatchback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interior.
        /// </summary>
        internal static string Interior {
            get {
                return ResourceManager.GetString("Interior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data.
        /// </summary>
        internal static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid state of odometer..
        /// </summary>
        internal static string InvalidOdoState {
            get {
                return ResourceManager.GetString("InvalidOdoState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided year is invalid..
        /// </summary>
        internal static string InvalidYear {
            get {
                return ResourceManager.GetString("InvalidYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LPG.
        /// </summary>
        internal static string LPG {
            get {
                return ResourceManager.GetString("LPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        internal static string Make {
            get {
                return ResourceManager.GetString("Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make:.
        /// </summary>
        internal static string MakeLabel {
            get {
                return ResourceManager.GetString("MakeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minivan.
        /// </summary>
        internal static string Minivan {
            get {
                return ResourceManager.GetString("Minivan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model:.
        /// </summary>
        internal static string ModelLabel {
            get {
                return ResourceManager.GetString("ModelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Note.
        /// </summary>
        internal static string NewNote {
            get {
                return ResourceManager.GetString("NewNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New vehicle.
        /// </summary>
        internal static string NewVehicle {
            get {
                return ResourceManager.GetString("NewVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next check at:.
        /// </summary>
        internal static string NextCheckAtLabel {
            get {
                return ResourceManager.GetString("NextCheckAtLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Notes..
        /// </summary>
        internal static string NoNotes {
            get {
                return ResourceManager.GetString("NoNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note for a .
        /// </summary>
        internal static string Notefor {
            get {
                return ResourceManager.GetString("Notefor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No vehicles..
        /// </summary>
        internal static string NoVehicles {
            get {
                return ResourceManager.GetString("NoVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer.
        /// </summary>
        internal static string OdometerTitle {
            get {
                return ResourceManager.GetString("OdometerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State of odometer:.
        /// </summary>
        internal static string OdoStateLabel {
            get {
                return ResourceManager.GetString("OdoStateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrol.
        /// </summary>
        internal static string Petrol {
            get {
                return ResourceManager.GetString("Petrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup.
        /// </summary>
        internal static string Pickup {
            get {
                return ResourceManager.GetString("Pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove this note?.
        /// </summary>
        internal static string ReallyRemove {
            get {
                return ResourceManager.GetString("ReallyRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove .
        /// </summary>
        internal static string ReallyRemoveVehicle {
            get {
                return ResourceManager.GetString("ReallyRemoveVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reg. Number.
        /// </summary>
        internal static string RegNum {
            get {
                return ResourceManager.GetString("RegNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reg. Number:.
        /// </summary>
        internal static string RegNumLabel {
            get {
                return ResourceManager.GetString("RegNumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sedan.
        /// </summary>
        internal static string Sedan {
            get {
                return ResourceManager.GetString("Sedan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supercar.
        /// </summary>
        internal static string Supercar {
            get {
                return ResourceManager.GetString("Supercar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUV.
        /// </summary>
        internal static string SUV {
            get {
                return ResourceManager.GetString("SUV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total distance driven.
        /// </summary>
        internal static string TotalOdoLabel {
            get {
                return ResourceManager.GetString("TotalOdoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reg. number and VIN need to be unique..
        /// </summary>
        internal static string UniqRegVIN {
            get {
                return ResourceManager.GetString("UniqRegVIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN.
        /// </summary>
        internal static string VIN {
            get {
                return ResourceManager.GetString("VIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN:.
        /// </summary>
        internal static string VINLabel {
            get {
                return ResourceManager.GetString("VINLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon.
        /// </summary>
        internal static string Wagon {
            get {
                return ResourceManager.GetString("Wagon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year:.
        /// </summary>
        internal static string YearLabel {
            get {
                return ResourceManager.GetString("YearLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
